<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>AsphyxiaRebreathed</RootNamespace>
    <AssemblyName>asphyxiarebreathed</AssemblyName>
    <OutputPath>bin\$(Configuration)\Mods\$(AssemblyName)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <VintageStoryPath Condition="'$(VintageStoryPath)' == '' and '$(VINTAGE_STORY)' != ''">$(VINTAGE_STORY)</VintageStoryPath>
    <VintageStoryPath Condition="'$(VintageStoryPath)' == ''">$(AppData)\Vintagestory</VintageStoryPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(VintageStoryPath)\Lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VintageStoryPath)\Lib\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VintageStoryPath)\Lib\protobuf-net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)\VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStoryPath)\VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VintageStoryPath)\Mods\VSCreativeMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VintageStoryPath)\Mods\VSEssentials.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VintageStoryPath)\Mods\VSSurvivalMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\launchSettings.json" />
    <Content Include="modinfo.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="assets\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>

